spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: book-service

server:
  port: 8080
  servlet:
    context-path: /api/bookmgmt
