spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderservice-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: online-bookstore-online-bookstore12.c.aivencloud.com:19928
    topic:
      order-events: order-events
      inventory-response: inventory-response
    properties:
      security.protocol: SSL
      ssl.keystore.type: PEM
      ssl.truststore.type: PEM
      ssl.keystore.location: D:/Java/certs/keystore.pem
      ssl.truststore.location: D:/Java/certs/ca.pem
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    context-path: /api
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

